import React, { createContext, useContext, useState } from 'react'

type Lang = 'en' | 'es'

interface LanguageContextType {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string) => string | Record<string, string>
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')

  const t = (key: string): string | Record<string, string> => {
    const value = translations[lang][key]
    return value !== undefined ? value : key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

const translations: Record<Lang, Record<string, any>> = {
  en: {
    'nav.brand': 'PABLO TOUR',
    'nav.tours': 'Our Tours',
    'nav.why': 'Why Pablo Tour',
    'nav.story': 'Our Story',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'hero.label': 'LOCAL FAMILY-RUN TOUR OPERATOR · AREQUIPA, PERU',
    'hero.title': 'Explore Colca Canyon With Those Who Know It Best',
    'hero.subtitle': 'Private & small-group treks along pre-Inca trails. No mass tourism. Just authentic routes, local guides, and 40 years of canyon heritage.',
    'hero.cta.primary': 'Ask on WhatsApp',
    'hero.cta.secondary': 'See Our Tours',
    'trust.local': 'Local Arequipa Operator',
    'trust.since': 'Colca Roots Since 1986',
    'trust.languages': 'English · Spanish · French',
    'trust.private': 'Private & Custom Groups',
    'why.label': 'WHY PABLO TOUR',
    'why.title': 'Not a Mass-Tour Agency. Not Even Close.',
    'why.p1': 'Most agencies pack 20 strangers on a bus. We design tours for your group, your pace, your interests. Our routes follow pre-Inca trails used by local families — paths that bypass the crowded viewpoints.',
    'why.p2': "Edwin Junco, your guide and our director, speaks Spanish, English, and French. He grew up in Cabanaconde on the canyon's edge. His father Pablo was the first guide in Colca. This isn't marketing — it's heritage.",
    'why.f1': 'Routes away from mass tourism',
    'why.f2': 'Pre-Inca trails with local context',
    'why.f3': 'Groups tailored to your fitness level',
    'why.f4': 'Culture + nature + adventure combined',
    'tours.label': 'OUR TOURS',
    'tours.title': 'Colca Canyon Experiences',
    'tours.subtitle': 'All tours include private transport, meals, accommodations, and a trilingual guide. No hidden costs. No mixed groups.',
    'tour.ask': 'Ask About This Tour',
    'tour.popular': 'MOST POPULAR',
    'tour.1.badge': '2 DAYS / 1 NIGHT',
    'tour.1.title': 'Colca Canyon Trek',
    'tour.1.subtitle': 'The essential canyon experience',
    'tour.1.desc': 'A shorter trek into the canyon along pre-Inca trails. Visit viewpoints, experience local life, and return with unforgettable memories.',
    'tour.1.meta': 'Moderate · Private Group',
    'tour.2.badge': '3 DAYS / 2 NIGHTS',
    'tour.2.title': 'Colca Canyon Trek',
    'tour.2.subtitle': 'The complete canyon immersion',
    'tour.2.desc': "Our most popular trek. Descend to the oasis, visit Huaruro waterfall, sleep in local family homes. The full Colca experience.",
    'tour.2.meta': 'Moderate to Challenging · Private Group',
    'tour.3.badge': '4 DAYS / 3 NIGHTS',
    'tour.3.title': 'Colca Canyon Trek',
    'tour.3.subtitle': 'Total immersion, deeper trails',
    'tour.3.desc': 'An extended trek exploring further into the canyon. More time for discovery, more connection with the landscape and local culture.',
    'tour.3.meta': 'Challenging · Private Group',
    'tour.4.badge': '2 DAYS / 1 NIGHT',
    'tour.4.title': 'Culture & Nature Tour',
    'tour.4.subtitle': 'Colca without the crowds',
    'tour.4.desc': 'A cultural route designed to avoid mass tourism. Visit the Achachihua viewpoint with no other tourists. Explore villages and terraces in peace.',
    'tour.4.meta': 'Easy to Moderate · Private Group',
    'tour.5.badge': '4 DAYS / 3 NIGHTS',
    'tour.5.title': 'Colca Mixed Adventure',
    'tour.5.subtitle': 'Bike + Trek + Raft',
    'tour.5.desc': 'The ultimate multi-sport adventure. Mountain bike descent into the canyon, trek to the oasis, then raft the Colca river. Previous biking experience recommended.',
    'tour.5.meta': 'Adventurous · Private Group · Min. Experience',
    'tour.6.badge': '4+ DAYS',
    'tour.6.title': 'Cotahuasi Canyon Expedition',
    'tour.6.subtitle': 'Beyond Colca — deeper still',
    'tour.6.desc': "One of the deepest canyons on Earth. 4x4 expedition through dramatic landscapes, stone forests, waterfalls, and Inca ruins. For true adventurers.",
    'tour.6.meta': 'Challenging · Private Group',
    'story.label': 'OUR STORY',
    'story.quote': 'The first guide in Colca built more than a trail — he built a legacy.',
    'story.p1': "In 1986, Paulino 'Pablo' Junco became the first guide in Cabanaconde, a village perched on the edge of Colca Canyon. A journalist by training and explorer by passion, Pablo believed tourism could transform his community. He created the first hostel in Cabanaconde — Valle del Fuego — and trained a generation of local guides.",
    'story.p2': 'Today, his son Edwin leads Pablo Tour from Arequipa. A trilingual guide with degrees from UNSA and UCSM, Edwin spent years leading tours for European operators before returning home. He brought world-class standards to a family operation — without losing the local soul that makes every tour authentic.',
    'story.stat1': 'Since 1986',
    'story.stat1Label': 'Cabanaconde Origins',
    'story.stat2': '40+ Years',
    'story.stat2Label': 'Canyon Experience',
    'story.stat3': 'Trilingual',
    'story.stat3Label': 'Personal Guidance',
    'diff.label': 'THE DIFFERENCE',
    'diff.title': 'Small Groups. Real Trails. Local Knowledge.',
    'diff.body': "We don't follow the standard bus route. Our trails are the same paths local families have used for centuries. You won't stand in a line of 50 people at Cruz del Condor — you'll watch condors soar in silence from a viewpoint only our guides know.",
    'diff.card1.title': 'Pre-Inca Trails',
    'diff.card1.desc': 'Walk paths carved before the Inca empire, still used by local communities today.',
    'diff.card2.title': 'Family-Run Hostel',
    'diff.card2.desc': 'Sleep at Valle del Fuego, our own hostel in Cabanaconde — the first in the village, built by Pablo in 1984.',
    'diff.card3.title': 'All-Inclusive, No Surprises',
    'diff.card3.desc': 'Transport, meals, accommodation, entries, oxygen, first-aid kit — everything included. Just bring water and snacks.',
    'gallery.label': 'GALLERY',
    'gallery.title': 'Colca Through Our Eyes',
    'faq.label': 'FAQ',
    'faq.title': 'Common Questions',
    'faq.q1': 'Can I book by WhatsApp?',
    'faq.a1': "Absolutely. Just send us a message with your travel dates and we'll recommend the best option for your schedule and fitness level.",
    'faq.q2': 'Can the tour be customized?',
    'faq.a2': 'Yes. Edwin will design a route based on your interests, physical condition, and time available. No two tours are identical.',
    'faq.q3': 'Is this suitable for beginners?',
    'faq.a3': 'We have options for all fitness levels. The 2-day Culture & Nature tour is ideal for beginners, while the 4-day Mixed Adventure requires prior biking experience.',
    'faq.q4': 'Do you offer private tours?',
    'faq.a4': 'All our tours are private. We never mix groups with other agencies. It\'s just your group and your guide.',
    'faq.q5': 'Can I continue to Puno or Cusco after?',
    'faq.a5': 'Yes. We organize connections to Southern Peru destinations. Ask us about combining your Colca trek with Puno or Cusco.',
    'faq.q6': 'What should I bring?',
    'faq.a6': 'Water, snacks, sunscreen, a flashlight, and swimwear for the hot springs. We provide everything else: transport, meals, accommodation, oxygen, and first-aid.',
    'faq.q7': 'What makes Pablo Tour different from classic tours?',
    'faq.a7': "Classic tours follow the standard bus route with 40+ people. Our trails are pre-Inca paths used by locals, reaching viewpoints and villages where standard tours don't go.",
    'faq.q8': 'When is the best time to visit?',
    'faq.a8': 'April to June is ideal. May to November is best for trekking. The rainy season (December–March) can make some trails more challenging.',
    'cta.title': 'Ready for Your Colca Adventure?',
    'cta.body': "Send us your travel dates and we'll suggest the best route for your group. No obligation, no pressure — just honest advice from a local guide.",
    'cta.button': 'Message Us on WhatsApp',
    'cta.email': 'Or email:',
    'footer.brand': 'PABLO TOUR',
    'footer.desc': 'Local family-run tour operator in Arequipa, Peru. Specialists in authentic Colca Canyon experiences since 1986.',
    'footer.contact': 'CONTACT',
    'footer.address': 'Jerusalén 400 AB-1, Arequipa, Peru',
    'footer.phone': '+51 941 414 048',
    'footer.email': 'perupablotour@gmail.com',
    'footer.links': 'QUICK LINKS',
    'footer.link.tours': 'Our Tours',
    'footer.link.why': 'Why Pablo Tour',
    'footer.link.faq': 'FAQ',
    'footer.link.contact': 'Contact Us',
    'footer.copyright': '© 2025 Pablo Tour E.I.R.L. All rights reserved.',
    'footer.demo': 'Demo concept — not the official Pablo Tour website.',
    'demo.banner': '⚠ This is a private demo for presentation purposes only. Not an official website. Images used as visual reference pending client authorization.',
  },
  es: {
    'nav.brand': 'PABLO TOUR',
    'nav.tours': 'Nuestros Tours',
    'nav.why': 'Por Qué Pablo Tour',
    'nav.story': 'Nuestra Historia',
    'nav.faq': 'Preguntas Frecuentes',
    'nav.contact': 'Contacto',
    'hero.label': 'OPERADOR LOCAL FAMILIAR · AREQUIPA, PERÚ',
    'hero.title': 'Explora el Cañón del Colca con quienes mejor lo conocen',
    'hero.subtitle': 'Trekking privado y en grupos pequeños por senderos pre-incas. Sin turismo masivo. Solo rutas auténticas, guías locales y 40 años de herencia en el cañón.',
    'hero.cta.primary': 'Pregunta por WhatsApp',
    'hero.cta.secondary': 'Ver Nuestros Tours',
    'trust.local': 'Operador Local de Arequipa',
    'trust.since': 'Raíces en el Colca desde 1986',
    'trust.languages': 'Español · Inglés · Francés',
    'trust.private': 'Grupos Privados y Personalizados',
    'why.label': 'POR QUÉ PABLO TOUR',
    'why.title': 'No somos una agencia de tours masivos. Ni cerca.',
    'why.p1': 'La mayoría de agencias mete 20 desconocidos en un bus. Nosotros diseñamos tours para tu grupo, tu ritmo, tus intereses. Nuestras rutas siguen senderos pre-incas usados por familias locales — caminos que evitan los miradores saturados.',
    'why.p2': 'Edwin Junco, tu guía y nuestro director, habla español, inglés y francés. Creció en Cabanaconde al borde del cañón. Su padre Pablo fue el primer guía en el Colca. Esto no es marketing — es herencia.',
    'why.f1': 'Rutas lejos del turismo masivo',
    'why.f2': 'Senderos pre-incas con contexto local',
    'why.f3': 'Grupos adaptados a tu condición física',
    'why.f4': 'Cultura + naturaleza + aventura combinadas',
    'tours.label': 'NUESTROS TOURS',
    'tours.title': 'Experiencias en el Cañón del Colca',
    'tours.subtitle': 'Todos los tours incluyen transporte privado, comidas, alojamiento y guía trilingüe. Sin costos ocultos. Sin grupos mezclados.',
    'tour.ask': 'Pregunta por este Tour',
    'tour.popular': 'MÁS POPULAR',
    'tour.1.badge': '2 DÍAS / 1 NOCHE',
    'tour.1.title': 'Trek Cañón del Colca',
    'tour.1.subtitle': 'La experiencia esencial del cañón',
    'tour.1.desc': 'Un trek más corto al cañón por senderos pre-incas. Visita miradores, experimenta la vida local y regresa con recuerdos inolvidables.',
    'tour.1.meta': 'Moderado · Grupo Privado',
    'tour.2.badge': '3 DÍAS / 2 NOCHES',
    'tour.2.title': 'Trek Cañón del Colca',
    'tour.2.subtitle': 'La inmersión completa en el cañón',
    'tour.2.desc': 'Nuestro trek más popular. Descenso al oasis, visita a la cascada Huaruro, noche en casa de familia local. La experiencia Colca completa.',
    'tour.2.meta': 'Moderado a Desafiante · Grupo Privado',
    'tour.3.badge': '4 DÍAS / 3 NOCHES',
    'tour.3.title': 'Trek Cañón del Colca',
    'tour.3.subtitle': 'Inmersión total, senderos más profundos',
    'tour.3.desc': 'Un trek extendido explorando más profundo el cañón. Más tiempo para descubrir, más conexión con el paisaje y la cultura local.',
    'tour.3.meta': 'Desafiante · Grupo Privado',
    'tour.4.badge': '2 DÍAS / 1 NOCHE',
    'tour.4.title': 'Tour Cultura y Naturaleza',
    'tour.4.subtitle': 'Colca sin las multitudes',
    'tour.4.desc': 'Una ruta cultural diseñada para evitar el turismo masivo. Visita el mirador Achachihua sin otros turistas. Explora pueblos y andeneros en paz.',
    'tour.4.meta': 'Fácil a Moderado · Grupo Privado',
    'tour.5.badge': '4 DÍAS / 3 NOCHES',
    'tour.5.title': 'Aventura Mixta Colca',
    'tour.5.subtitle': 'Bici + Trek + Rafting',
    'tour.5.desc': 'La aventura multideporte definitiva. Descenso en bicicleta al cañón, trek al oasis y rafting en el río Colca. Se recomienda experiencia previa en ciclismo.',
    'tour.5.meta': 'Aventurero · Grupo Privado · Exp. Mínima',
    'tour.6.badge': '4+ DÍAS',
    'tour.6.title': 'Expedición Cañón de Cotahuasi',
    'tour.6.subtitle': 'Más allá del Colca — más profundo aún',
    'tour.6.desc': 'Uno de los cañones más profundos de la Tierra. Expedición en 4x4 por paisajes dramáticos, bosques de piedra, cascadas y ruinas incas. Para verdaderos aventureros.',
    'tour.6.meta': 'Desafiante · Grupo Privado',
    'story.label': 'NUESTRA HISTORIA',
    'story.quote': 'El primer guía en el Colca construyó más que un sendero — construyó un legado.',
    'story.p1': "En 1986, Paulino 'Pablo' Junco se convirtió en el primer guía en Cabanaconde, un pueblo al borde del Cañón del Colca. Periodista de formación y explorador de pasión, Pablo creyó que el turismo podría transformar su comunidad. Creó el primer hostal en Cabanaconde — Valle del Fuego — y entrenó una generación de guías locales.",
    'story.p2': 'Hoy, su hijo Edwin dirige Pablo Tour desde Arequipa. Guía trilingüe con títulos de la UNSA y la UCSM, Edwin pasó años liderando tours para operadores europeos antes de regresar a casa. Trajo estándares de clase mundial a una operación familiar — sin perder el alma local que hace cada tour auténtico.',
    'story.stat1': 'Desde 1986',
    'story.stat1Label': 'Orígenes en Cabanaconde',
    'story.stat2': '40+ Años',
    'story.stat2Label': 'Experiencia en el Cañón',
    'story.stat3': 'Trilingüe',
    'story.stat3Label': 'Guía Personal',
    'diff.label': 'LA DIFERENCIA',
    'diff.title': 'Grupos Pequeños. Senderos Reales. Conocimiento Local.',
    'diff.body': 'No seguimos la ruta estándar del bus. Nuestros senderos son los mismos caminos que las familias locales han usado por siglos. No estarás en una fila de 50 personas en la Cruz del Cóndor — verás cóndores volar en silencio desde un mirador que solo nuestros guías conocen.',
    'diff.card1.title': 'Senderos Pre-Inca',
    'diff.card1.desc': 'Camina por senderos tallados antes del imperio inca, aún usados por comunidades locales.',
    'diff.card2.title': 'Hostal Familiar',
    'diff.card2.desc': 'Duerme en Valle del Fuego, nuestro propio hostal en Cabanaconde — el primero del pueblo, construido por Pablo en 1984.',
    'diff.card3.title': 'Todo Incluido, Sin Sorpresas',
    'diff.card3.desc': 'Transporte, comidas, alojamiento, entradas, oxígeno, botiquín — todo incluido. Solo trae agua y snacks.',
    'gallery.label': 'GALERÍA',
    'gallery.title': 'El Colca a través de nuestros ojos',
    'faq.label': 'PREGUNTAS FRECUENTES',
    'faq.title': 'Preguntas Comunes',
    'faq.q1': '¿Puedo reservar por WhatsApp?',
    'faq.a1': 'Por supuesto. Envíanos un mensaje con tus fechas de viaje y te recomendaremos la mejor opción según tu agenda y condición física.',
    'faq.q2': '¿Se puede personalizar el tour?',
    'faq.a2': 'Sí. Edwin diseñará una ruta según tus intereses, condición física y tiempo disponible. No dos tours son idénticos.',
    'faq.q3': '¿Es apto para principiantes?',
    'faq.a3': 'Tenemos opciones para todos los niveles. El tour de Cultura y Naturaleza de 2 días es ideal para principiantes, mientras que la Aventura Mixta de 4 días requiere experiencia previa en ciclismo.',
    'faq.q4': '¿Ofrecen tours privados?',
    'faq.a4': 'Todos nuestros tours son privados. Nunca mezclamos grupos con otras agencias. Es solo tu grupo y tu guía.',
    'faq.q5': '¿Puedo continuar a Puno o Cusco después?',
    'faq.a5': 'Sí. Organizamos conexiones hacia destinos del Sur del Perú. Consúltanos por combinaciones de tu trek en el Colca con Puno o Cusco.',
    'faq.q6': '¿Qué debo traer?',
    'faq.a6': 'Agua, snacks, protector solar, una linterna y traje de baño para las aguas termales. Nosotros proveemos todo lo demás: transporte, comidas, alojamiento, oxígeno y botiquín.',
    'faq.q7': '¿Qué hace diferente a Pablo Tour de los tours clásicos?',
    'faq.a7': 'Los tours clásicos siguen la ruta estándar del bus con 40+ personas. Nuestros senderos son caminos pre-incas usados por locales, alcanzando miradores y pueblos donde los tours estándar no llegan.',
    'faq.q8': '¿Cuándo es la mejor época para visitar?',
    'faq.a8': 'Abril a junio es ideal. Mayo a noviembre es mejor para trekking. La temporada de lluvias (diciembre–marzo) puede dificultar algunos senderos.',
    'cta.title': '¿Listo para tu Aventura en el Colca?',
    'cta.body': 'Envíanos tus fechas de viaje y te sugeriremos la mejor ruta para tu grupo. Sin compromiso, sin presión — solo consejo honesto de un guía local.',
    'cta.button': 'Escríbenos por WhatsApp',
    'cta.email': 'O por email:',
    'footer.brand': 'PABLO TOUR',
    'footer.desc': 'Operador turístico local familiar en Arequipa, Perú. Especialistas en experiencias auténticas en el Cañón del Colca desde 1986.',
    'footer.contact': 'CONTACTO',
    'footer.address': 'Jerusalén 400 AB-1, Arequipa, Perú',
    'footer.phone': '+51 941 414 048',
    'footer.email': 'perupablotour@gmail.com',
    'footer.links': 'LINKS RÁPIDOS',
    'footer.link.tours': 'Nuestros Tours',
    'footer.link.why': 'Por Qué Pablo Tour',
    'footer.link.faq': 'Preguntas Frecuentes',
    'footer.link.contact': 'Contáctanos',
    'footer.copyright': '© 2025 Pablo Tour E.I.R.L. Todos los derechos reservados.',
    'footer.demo': 'Demo conceptual — no es el sitio oficial de Pablo Tour.',
    'demo.banner': '⚠ Esta es una demo privada solo para fines de presentación. No es un sitio web oficial. Las imágenes se usan como referencia visual a la espera de autorización del cliente.',
  },
}
